[project]
name = 'Elder-Care-Safety-Companion'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.fall-detection-and-response]
path = 'contracts/fall-detection-and-response.clar'
clarity_version = 3
epoch = '3.2'

[contracts.medication-adherence-tracking]
path = 'contracts/medication-adherence-tracking.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
